// <auto-generated />
namespace OHET_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuickFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuickFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201810151545030_QuickFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
